database:
  driverClass: com.mysql.jdbc.Driver
  user: root 
  password: changeme 
  url: jdbc:mysql://localhost/test

server:
  rootPath: /*
  applicationConnectors:
    - type: http
      port: 9000 
  adminConnectors:
      - type: http
        port: 8081

logging:
  loggers:
    org.glassfish.jersey.filter.LoggingFilter: INFO
