couchbase:
  bucket: default
  hosts:
    - http://couchbase0.local:8091/pools
  password: changeme

server:
  rootPath: /*
  applicationConnectors:
    - type: http
      port: 9000 
  adminConnectors:
      - type: http
        port: 8081

logging:
  loggers:
    org.glassfish.jersey.filter.LoggingFilter: ERROR
    hibernate.session.events.log: false
