database:
  driverClass: com.mysql.jdbc.Driver
  user: cse391
  password: password
  url: jdbc:mysql://localhost/test

server:
  rootPath: /*
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
      - type: http
        port: 8081

logging:
  loggers:
    org.glassfish.jersey.filter.LoggingFilter: INFO
